# Generated by Django 4.0.2 on 2022-02-13 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Округ')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Округ')),
                ('description', models.TextField(verbose_name='Описание')),
                ('type', models.CharField(choices=[('park', 'Парк'), ('unique_place', 'Особое место'), ('restaurant', 'Ресторан')], max_length=30, verbose_name='Тип места')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.districts')),
            ],
        ),
    ]
