# Generated by Django 4.0.2 on 2022-02-16 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_place_image_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='image',
        ),
    ]
