# Generated by Django 4.0.2 on 2022-02-19 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_remove_place_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='description',
            new_name='full_description',
        ),
    ]
