# Generated by Django 4.0.2 on 2022-02-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_rename_description_place_full_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='short_description',
            field=models.TextField(default='', verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='full_description',
            field=models.TextField(default='', verbose_name='Полное писание'),
        ),
    ]
