# Generated by Django 4.0.2 on 2022-02-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_districts_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='place',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9, verbose_name='Широта'),
        ),
    ]
